import { z } from "zod";

const faqSchema = z.object({
  question: z.string().min(3),
  answer: z.string().min(3),
});

export const loginSchema = z.object({
  password: z.string().min(1, "Password is required"),
});

/*
 * Schema used by the server when publishing a blog.
 *
 * The image URL/path is optional here because the server
 * generates it automatically after uploading imageFile
 * to GitHub.
 */
export const publishBlogSchema = z.object({
  title: z.string().min(3, "Title is required"),

  slug: z
    .string()
    .min(2, "Slug is required")
    .regex(
      /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
      "Slug must be lowercase and hyphenated"
    ),

  description: z.string().min(10, "Description is required"),

  category: z.string().min(2, "Category is required"),

  author: z.string().min(2, "Author is required"),

  tags: z
    .union([z.string(), z.array(z.string())])
    .optional(),

  /*
   * Image path is generated by the server after
   * imageFile is uploaded to GitHub.
   */
  image: z.string().optional().default(""),

  imageAlt: z.string().optional(),

  seoTitle: z.string().optional(),

  seoDescription: z.string().optional(),

  keyTakeaways: z
    .union([z.string(), z.array(z.string())])
    .optional(),

  faqs: z.array(faqSchema).optional(),

  markdown: z
    .string()
    .min(20, "Markdown content is required"),
});

export type PublishBlogInput =
  z.infer<typeof publishBlogSchema>;

/*
 * Schema used by the admin page.
 *
 * The user selects an actual image file, so there is
 * no need to enter an image URL/path.
 */
export const publishBlogFormSchema = z.object({
  title: z.string().min(3, "Title is required"),

  slug: z
    .string()
    .min(2, "Slug is required")
    .regex(
      /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
      "Slug must be lowercase and hyphenated"
    ),

  description: z.string().min(10, "Description is required"),

  category: z.string().min(2, "Category is required"),

  author: z.string().min(2, "Author is required"),

  tags: z.string().optional(),

  /*
   * No image URL is required in the admin form.
   */
  image: z.string().optional().default(""),

  imageAlt: z.string().optional(),

  seoTitle: z.string().optional(),

  seoDescription: z.string().optional(),

  keyTakeaways: z.string().optional(),

  markdown: z
    .string()
    .min(20, "Markdown content is required"),
});

export type PublishBlogFormValues =
  z.infer<typeof publishBlogFormSchema>;

export function normalizeTagsInput(
  tags: string | string[] | undefined
): string[] {
  if (!tags) return [];

  if (Array.isArray(tags)) {
    return tags
      .map((tag) => tag.trim())
      .filter(Boolean);
  }

  return tags
    .split(",")
    .map((tag) => tag.trim())
    .filter(Boolean);
}

export function normalizeTakeawaysInput(
  value: string | string[] | undefined
): string[] {
  if (!value) return [];

  if (Array.isArray(value)) {
    return value
      .map((item) => item.trim())
      .filter(Boolean);
  }

  return value
    .split(/\n/)
    .map((item) =>
      item.replace(/^[-*]\s*/, "").trim()
    )
    .filter(Boolean);
}